### ISSUE TITLE
Error & warning messages on console

### ISSUE THREAD

**Issue by FrostXTJ** [andyzhou1999/csci-401-capstone#4]
There are a couple of error and warning messages logged on console. It seems they are not blocking the app from working properly but it is better to fix it:

Recommendation Page:
![image](https://user-images.githubusercontent.com/41350819/134039602-e0a30f36-8fb3-4afc-b9c3-680a82cb9bbd.png)

Template Page:
![image](https://user-images.githubusercontent.com/41350819/134039655-94d098db-8f81-403c-99cb-5586290dff87.png)

**Comment by andrewhan324** [comment]
Fixed the issue #4

For the recommendation error, the order of library import was the issue. jquery should be imported first before bootstrap

For the template error, it seems previous group tried to use another button (Add Template) instead of 'Create Template' button we already have. So I just commented out that part.
